version: '3.9'

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: elementalsouls
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: <CHANGE_ME>
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  comfyui:
    image: ghcr.io/comfyanonymous/comfyui:latest
    restart: unless-stopped
    environment:
      - CLI_ARGS=--listen 0.0.0.0 --port 8188
    ports:
      - '8188:8188'
    volumes:
      - comfyui_data:/root/ComfyUI/custom_nodes
    profiles:
      - ai

volumes:
  postgres_data:
  redis_data:
  comfyui_data:
